### ISSUE TITLE
Small issue with grunt file

### ISSUE THREAD

**Issue by brunowego** [virtyaluk/grunt-iife#1]
Hello @virtyaluk, you have a nice plugin here, congrats. I get small issue with `grunt.file.exist`, I did a research and I finding in http://gruntjs.com/api/grunt.file and the correct function is `grunt.file.exists`.

But I not know if this issue is because the version of grunt.

``` bash
grunt iife                                                                                                                                                             
Running "iife:dist" (iife) task
Warning: grunt.file.exist is not a function Use --force to continue.
```

See my module:

``` bash
module.exports = {
    dist: {
        files: {
            './src/scripts/chip.js': './dist/scripts/chip.js'
        }
    }
};
```

You can tell me where I mistake?

**Comment by virtyaluk** [comment]
Nice catch, @brunowego :+1: 
Thank you for your feedback. It's very important to me.

You're right, there was an issue with the name of the function. I've fixed the issue.
Updated version of the package is already waiting for you.

**Comment by brunowego** [comment]
Quickly fix, thank you!
